/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.io.quarkus.quarkus.resteasy.reactive.jackson)
    implementation(libs.dev.langchain4j.langchain4j.ollama)
    implementation(libs.io.quarkus.quarkus.resteasy.reactive)
    implementation(libs.io.quarkus.quarkus.arc)

    testImplementation(libs.io.quarkus.quarkus.junit5)
    testImplementation(libs.io.rest.assured.rest.assured)
}

group = "org.acme"
version = "1.0.0-SNAPSHOT"
description = "quarkus-langchain"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
